# Write your MySQL query statement below
SELECT CUSTOMER_NUMBER FROM ORDERS GROUP BY CUSTOMER_NUMBER HAVING COUNT(ORDER_NUMBER) = 
(SELECT MAX(ORDER_COUNT) FROM (SELECT COUNT(ORDER_NUMBER) AS ORDER_COUNT FROM ORDERS GROUP BY CUSTOMER_NUMBER) as temp)